name: Export Godot APK

on:
  push:
    branches: [ main ]

jobs:
  export:
    name: Export APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Godot exporter
        uses: firebelley/godot-export@v4
        with:
          godot-version: 4.2.2
          export-preset: "Android"
          use-godot-export-templates: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UltimateShooter-APK
          path: UltimateShooter.apk
