name: Build Godot Android APK

on:
  push:
    branches: [ main ]

jobs:
  export-apk:
    name: Export Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Godot headless
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux_headless.64.zip
          unzip Godot_v4.2.2-stable_linux_headless.64.zip
          mv Godot_v4.2.2-stable_linux_headless.64 godot
          chmod +x godot

      - name: Download Android export templates
        run: |
          mkdir -p ~/.local/share/godot/templates/4.2.2.stable
          wget https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          tar -xf Godot_v4.2.2-stable_export_templates.tpz -C ~/.local/share/godot/templates/4.2.2.stable

      - name: Export APK
        run: |
          ./godot --headless --export-release Android UltimateShooter.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: UltimateShooter-APK
          path: UltimateShooter.apk
